package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 11:55:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone59 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone59() throws CloneNotSupportedException {    // Kirja: 59
    Kirja kirja = new Kirja(); 
    kirja.parse("2  |  Taru sormusten herrasta  |  J R Tolkien  "); 
    Kirja kopio = kirja.clone(); 
    assertEquals("From: Kirja line: 64", kirja.toString(), kopio.toString()); 
    kirja.parse("3  |  Taru herrasta  |  Tolkien  "); 
    assertEquals("From: Kirja line: 66", false, kopio.toString().equals(kirja.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse95 */
  @Test
  public void testParse95() {    // Kirja: 95
    Kirja kirja = new Kirja(); 
    kirja.parse("2  |  Taru sormusten herrasta  |  J R Tolkien  "); 
    assertEquals("From: Kirja line: 98", 2, kirja.getKirjanID()); 
    assertEquals("From: Kirja line: 99", true, kirja.toString().startsWith("2|Taru sormusten herrasta|J R Tolkien|")); 
    kirja.rekisteroi(); 
    int n = kirja.getKirjanID(); 
    kirja.parse("" + (n+20)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 105", n+20+1, kirja.getKirjanID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi144 */
  @Test
  public void testRekisteroi144() {    // Kirja: 144
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 146", 0, kirja1.getKirjanID()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjanID(); 
    int n2 = kirja2.getKirjanID(); 
    assertEquals("From: Kirja line: 152", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString166 */
  @Test
  public void testToString166() {    // Kirja: 166
    Kirja kirja = new Kirja(); 
    kirja.parse("2  |  Taru sormusten herrasta  |  J R Tolkien  "); 
    assertEquals("From: Kirja line: 169", true, kirja.toString().startsWith("2|Taru sormusten herrasta|J R Tolkien|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetKentta233 */
  @Test
  public void testSetKentta233() {    // Kirja: 233
    Kirja kirja = new Kirja(); 
    kirja.setKentta(0, "testinimi"); 
    assertEquals("From: Kirja line: 236", "testinimi", kirja.getKentta(0)); 
    kirja.setKentta(2, "Suomi"); 
    assertEquals("From: Kirja line: 238", "Suomi", kirja.getKentta(2)); 
    assertEquals("From: Kirja line: 239", "Vuosiluku on väärin", kirja.setKentta(4, "5000")); 
    assertEquals("From: Kirja line: 240", "Sivumäärä ei ole oikeaa muotoa!", kirja.setKentta(6, "-45")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaSivut264 */
  @Test
  public void testTarkistaSivut264() {    // Kirja: 264
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 266", null, kirja.tarkistaSivut("12")); 
    assertEquals("From: Kirja line: 267", "Sivumäärä ei ole oikeaa muotoa!", kirja.tarkistaSivut("sfasdf")); 
    assertEquals("From: Kirja line: 268", "Sivumäärä ei ole oikeaa muotoa!", kirja.tarkistaSivut("-45")); 
    assertEquals("From: Kirja line: 269", null, kirja.tarkistaSivut("566")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaVuosi285 */
  @Test
  public void testTarkistaVuosi285() {    // Kirja: 285
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 287", null, kirja.tarkistaVuosi("100")); 
    assertEquals("From: Kirja line: 288", "Vuosiluku on väärin", kirja.tarkistaVuosi("5000")); 
    assertEquals("From: Kirja line: 289", "Anna vuosiluku muodossa vvvv!", kirja.tarkistaVuosi("-1")); 
    assertEquals("From: Kirja line: 290", null, kirja.tarkistaVuosi("1954")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKentta307 */
  @Test
  public void testGetKentta307() {    // Kirja: 307
    Kirja kirja = new Kirja(); 
    kirja.setKentta(0, "testinimi"); 
    assertEquals("From: Kirja line: 310", "testinimi", kirja.getKentta(0)); 
    kirja.setKentta(2, "Suomi"); 
    assertEquals("From: Kirja line: 312", "Suomi", kirja.getKentta(2)); 
    kirja.setKentta(6, "767"); 
    assertEquals("From: Kirja line: 314", "767", kirja.getKentta(6)); 
  } // Generated by ComTest END
}