package kirjasto.test;
// Generated by ComTest BEGIN
import java.util.ArrayList;
import java.util.*;
import java.io.*;
import java.io.File;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 13:17:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {
    //



  // Generated by ComTest BEGIN
  /** 
   * testEtsi91 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi91() throws SailoException {    // Kirjasto: 91
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirja1.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|1993|otava|123-456-0-33333-2| kauhu|"); 
    Kirja kirja2 = new Kirja(); kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |2004|WSOY|343-467-0-23456-1 | fantasia|"); 
    Kirja kirja3 = new Kirja(); kirja3.parse("3|Tuntematon sotilas      |kissa kirjoittaja |suomi   |1985|WSOY|752-123-2-34658-5 | kaunokirjallisuus|"); 
    Kirja kirja4 = new Kirja(); kirja4.parse("4|Rautatie                |Juhani Aho|"); 
    Kirja kirja5 = new Kirja(); kirja5.parse("5|Harry Potter            |Rowling           |suomi|"); 
    kirjasto.lisaa(kirja1); kirjasto.lisaa(kirja2); kirjasto.lisaa(kirja3); kirjasto.lisaa(kirja4); kirjasto.lisaa(kirja5); 
    ArrayList<Kirja> loytyneet = new  ArrayList<Kirja>(); 
    loytyneet = kirjasto.etsi("*rr*",0); 
    assertEquals("From: Kirjasto line: 103", 2, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 104", true, loytyneet.get(0) == kirja1); 
    assertEquals("From: Kirjasto line: 105", true, loytyneet.get(1) == kirja5); 
    loytyneet = kirjasto.etsi("*suo*",2); 
    assertEquals("From: Kirjasto line: 107", 3, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 108", true, loytyneet.get(0) == kirja2); 
    assertEquals("From: Kirjasto line: 109", true, loytyneet.get(1) == kirja3); 
    assertEquals("From: Kirjasto line: 110", true, loytyneet.get(2) == kirja5); 
    loytyneet = kirjasto.etsi(null,-1); 
    assertEquals("From: Kirjasto line: 112", 5, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaKirja124 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaKirja124() throws SailoException {    // Kirjasto: 124
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kir1 = new Kirja(), kir2 = new Kirja(), kir3 = new Kirja(); 
    kir1.rekisteroi(); kir2.rekisteroi(); kir3.rekisteroi(); 
    kirjasto.lisaa(kir1); kirjasto.lisaa(kir2); kirjasto.lisaa(kir3); 
    assertEquals("From: Kirjasto line: 130", 3, kirjasto.getKirjoja()); 
    kirjasto.poistaKirja(kir1); 
    assertEquals("From: Kirjasto line: 132", 2, kirjasto.getKirjoja()); 
    kirjasto.poistaKirja(kir2); 
    assertEquals("From: Kirjasto line: 134", 1, kirjasto.getKirjoja()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaKommentti148 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaKommentti148() throws SailoException {    // Kirjasto: 148
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirjasto.lisaa(kirja1); 
    Kirja kirja2 = new Kirja(); kirjasto.lisaa(kirja2); 
    kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |WSOY |2004|343-467-0-23456-1 |200 |fantasia|"); 
    Kommentti kom11 = new Kommentti(2); kirjasto.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(1); kirjasto.lisaa(kom22); 
    Kommentti kom33 = new Kommentti(2); kirjasto.lisaa(kom33); 
    kom11.parse("4  | 2 |  otsikko2  |  tekstiätekstiä  "); 
    kom22.parse("5  | 2 |  otsikko21  |  tekstiätekstiä  "); 
    kom33.parse("3  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    List<Kommentti> loytyneet; 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 163", 3, loytyneet.size()); 
    kirjasto.poistaKommentti(kom22); 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 166", 2, loytyneet.size()); 
    kirjasto.poistaKommentti(kom11); 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 169", 1, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta182 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta182() throws SailoException {    // Kirjasto: 182
    String hakemisto = "testikirjasto"; 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    String kirjat = "testikirjasto/kirjat.dat"; 
    String kommentit = "testikirjasto/kommentit.dat"; 
    File ftied1 = new File(kirjat); 
    File ftied2 = new File(kommentit); 
    ftied1.delete(); 
    ftied2.delete(); 
    Kirjasto kirjasto = new Kirjasto(); 
    try {
    kirjasto.lueTiedostosta(hakemisto); 
    fail("Kirjasto: 196 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Kirja kirja1 = new Kirja(); kirjasto.lisaa(kirja1); 
    Kirja kirja2 = new Kirja(); kirjasto.lisaa(kirja2); 
    Kirja kirja3 = new Kirja(); kirjasto.lisaa(kirja3); 
    kirja1.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|otava|1993|123-456-0-33333-2 |150 | kauhu|"); 
    kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |WSOY |2004|343-467-0-23456-1 |200 |fantasia|"); 
    kirja3.parse("3|Tuntematon sotilas      |essi esimerkki    |suomi   |WSOY |1985|752-123-2-34658-5 |489 |kaunokirjallisuus|"); 
    Kommentti kom1 = new Kommentti(); kirjasto.lisaa(kom1); 
    Kommentti kom2 = new Kommentti(); kirjasto.lisaa(kom2); 
    Kommentti kom3 = new Kommentti(); kirjasto.lisaa(kom3); 
    kom1.parse("4  | 2 |  otsikko2  |  tekstiätekstiä  "); 
    kom2.parse("5  | 1 |  otsikko21  |  tekstiätekstiä  "); 
    kom3.parse("3  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    kirjasto.tallenna(); 
    kirjasto = new Kirjasto(); 
    kirjasto.setTiedosto(hakemisto); 
    kirjasto.lueTiedostosta(hakemisto); 
    List<Kommentti> loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 215", 2, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 216", kirja1.toString(), kirjasto.annaKirja(0).toString()); 
    assertEquals("From: Kirjasto line: 217", kirja3.toString(), kirjasto.annaKirja(2).toString()); 
    assertEquals("From: Kirjasto line: 218", true, ftied1.delete()); 
    assertEquals("From: Kirjasto line: 219", true, ftied2.delete()); 
    assertEquals("From: Kirjasto line: 220", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKommentit276 */
  @Test
  public void testAnnaKommentit276() {    // Kirjasto: 276
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirja1.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|1993|otava|123-456-0-33333-2| kauhu|"); 
    Kirja kirja2 = new Kirja(); kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |2004|WSOY|343-467-0-23456-1 | fantasia|"); 
    Kirja kirja3 = new Kirja(); kirja3.parse("5|Tuntematon sotilas      |kissa kirjoittaja |suomi   |1985|WSOY|752-123-2-34658-5 | kaunokirjallisuus|"); 
    Kirja kirja4 = new Kirja(); 
    Kommentti kom11 = new Kommentti(2); kirjasto.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(1); kirjasto.lisaa(kom22); 
    Kommentti kom33 = new Kommentti(2); kirjasto.lisaa(kom33); 
    Kommentti kom44 = new Kommentti(1); kirjasto.lisaa(kom44); 
    Kommentti kom55 = new Kommentti(2); kirjasto.lisaa(kom55); 
    Kommentti kom66 = new Kommentti(5); kirjasto.lisaa(kom66); 
    List<Kommentti> loytyneet; 
    loytyneet = kirjasto.annaKommentit(kirja4); 
    assertEquals("From: Kirjasto line: 291", 0, loytyneet.size()); 
    loytyneet = kirjasto.annaKommentit(kirja1); 
    assertEquals("From: Kirjasto line: 293", 2, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 294", true, loytyneet.get(0) == kom22); 
    assertEquals("From: Kirjasto line: 295", true, loytyneet.get(1) == kom44); 
    loytyneet = kirjasto.annaKommentit(kirja3); 
    assertEquals("From: Kirjasto line: 297", 1, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 298", true, loytyneet.get(0) == kom66); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa310 */
  @Test
  public void testLisaa310() {    // Kirjasto: 310
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirja1.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|1993|otava|123-456-0-33333-2| kauhu|"); 
    Kirja kirja2 = new Kirja(); kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |2004|WSOY|343-467-0-23456-1 | fantasia|"); 
    Kirja kirja3 = new Kirja(); kirja3.parse("5|Tuntematon sotilas      |kissa kirjoittaja |suomi   |1985|WSOY|752-123-2-34658-5 | kaunokirjallisuus|"); 
    Kirja kirja4 = new Kirja(); 
    Kommentti kom11 = new Kommentti(2); kirjasto.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(1); kirjasto.lisaa(kom22); 
    Kommentti kom33 = new Kommentti(2); kirjasto.lisaa(kom33); 
    Kommentti kom44 = new Kommentti(1); kirjasto.lisaa(kom44); 
    Kommentti kom55 = new Kommentti(2); kirjasto.lisaa(kom55); 
    Kommentti kom66 = new Kommentti(5); kirjasto.lisaa(kom66); 
    List<Kommentti> loytyneet; 
    loytyneet = kirjasto.annaKommentit(kirja4); 
    assertEquals("From: Kirjasto line: 325", 0, loytyneet.size()); 
    loytyneet = kirjasto.annaKommentit(kirja1); 
    assertEquals("From: Kirjasto line: 327", 2, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 328", true, loytyneet.get(0) == kom22); 
    assertEquals("From: Kirjasto line: 329", true, loytyneet.get(1) == kom44); 
    loytyneet = kirjasto.annaKommentit(kirja3); 
    assertEquals("From: Kirjasto line: 331", 1, loytyneet.size()); 
    assertEquals("From: Kirjasto line: 332", true, loytyneet.get(0) == kom66); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa344 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa344() throws SailoException {    // Kirjasto: 344
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja11 = new Kirja(); kirjasto.lisaa(kirja11); 
    Kirja kirja22 = new Kirja(); kirjasto.lisaa(kirja22); 
    kirja11.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|1993|otava|123-456-0-33333-2| kauhu|"); 
    kirja22.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |2004|WSOY|343-467-0-23456-1 | fantasia|"); 
    Kirja kirja33 = new Kirja(); 
    kirja33.parse("3|Tuntematon sotilas      |kissa kirjoittaja |suomi   |1985|WSOY|752-123-2-34658-5 | kaunokirjallisuus|"); 
    Kirja kirja44 = new Kirja(); 
    kirja44.parse("1|Rautatie |Juhani Aho|"); 
    assertEquals("From: Kirjasto line: 355", kirja11, kirjasto.annaKirja(0)); 
    kirjasto.korvaaTaiLisaa(kirja33); 
    assertEquals("From: Kirjasto line: 357", kirja33, kirjasto.annaKirja(2)); 
    assertEquals("From: Kirjasto line: 358", 3, kirjasto.getKirjoja()); 
    kirjasto.korvaaTaiLisaa(kirja44); 
    assertEquals("From: Kirjasto line: 360", kirja44.toString(), kirjasto.annaKirja(0).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa373 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa373() throws SailoException {    // Kirjasto: 373
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |2004|WSOY|343-467-0-23456-1 | fantasia|"); 
    Kommentti kom11 = new Kommentti(2); kirjasto.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(2); kirjasto.lisaa(kom22); 
    kom11.parse("1  | 2 |  testi1  |  tekstiä1  "); 
    kom22.parse("2  | 2 |  testi2  |  tekstiä2  "); 
    Kommentti kom33 = new Kommentti(2); 
    kom33.parse("3  | 2 |  testi3  |  tekstiä3  "); 
    Kommentti kom44 = new Kommentti(2); 
    kom44.parse("1  | 2 |  testi4  |  tekstiä4  "); 
    List<Kommentti> loytyneet; 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 389", "testi1", loytyneet.get(0).getOtsikko()); 
    kirjasto.korvaaTaiLisaa(kom33); 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 392", 3, loytyneet.size()); 
    kirjasto.korvaaTaiLisaa(kom44); 
    loytyneet = kirjasto.annaKommentit(kirja2); 
    assertEquals("From: Kirjasto line: 395", "testi4", loytyneet.get(0).getOtsikko()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaKirja409 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaKirja409() throws SailoException {    // Kirjasto: 409
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirja1.taytaKirjanTiedot(); 
    Kirja kirja2 = new Kirja(); kirja2.taytaKirjanTiedot(); 
    Kirja kirja3 = new Kirja(); kirja3.taytaKirjanTiedot(); 
    Kirja kirja4 = new Kirja(); kirja4.taytaKirjanTiedot(); 
    Kirja kirja5 = new Kirja(); kirja5.taytaKirjanTiedot(); 
    kirjasto.lisaa(kirja1); 
    kirjasto.lisaa(kirja2); 
    kirjasto.lisaa(kirja3); 
    kirjasto.lisaa(kirja4); 
    kirjasto.lisaa(kirja5); 
    assertEquals("From: Kirjasto line: 423", kirja1.toString(), kirjasto.annaKirja(0).toString()); 
    assertEquals("From: Kirjasto line: 424", kirja3.toString(), kirjasto.annaKirja(2).toString()); 
    assertEquals("From: Kirjasto line: 425", kirja5.toString(), kirjasto.annaKirja(4).toString()); 
    assertEquals("From: Kirjasto line: 426", kirja2, kirjasto.annaKirja(1)); 
    assertEquals("From: Kirjasto line: 427", kirja4, kirjasto.annaKirja(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa449 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa449() throws SailoException {    // Kirjasto: 449
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjasto line: 453", 0, kirjasto.getKirjoja()); 
    kirjasto.lisaa(kirja1); assertEquals("From: Kirjasto line: 454", 1, kirjasto.getKirjoja()); 
    kirjasto.lisaa(kirja2); assertEquals("From: Kirjasto line: 455", 2, kirjasto.getKirjoja()); 
    kirjasto.lisaa(kirja1); assertEquals("From: Kirjasto line: 456", 3, kirjasto.getKirjoja()); 
    assertEquals("From: Kirjasto line: 457", kirja1, kirjasto.annaKirja(0)); 
    assertEquals("From: Kirjasto line: 458", kirja2, kirjasto.annaKirja(1)); 
    assertEquals("From: Kirjasto line: 459", kirja1, kirjasto.annaKirja(2)); 
    assertEquals("From: Kirjasto line: 460", false, kirjasto.annaKirja(1) == kirja1); 
    assertEquals("From: Kirjasto line: 461", true, kirjasto.annaKirja(1) == kirja2); 
    try {
    assertEquals("From: Kirjasto line: 462", kirja1, kirjasto.annaKirja(3)); 
    fail("Kirjasto: 462 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLaskeTilastot500 
   * @throws SailoException when error
   */
  @Test
  public void testLaskeTilastot500() throws SailoException {    // Kirjasto: 500
    ByteArrayOutputStream outContent = new ByteArrayOutputStream(); 
    PrintStream ps = new PrintStream(outContent, true); 
    Kirjasto kirjasto = new Kirjasto(); 
    Kirja kirja1 = new Kirja(); kirja1.parse("1|taru sormusten herrasta |essi esimerkki    |englanti|otava|1993|123-456-0-33333-2 |150 | kauhu|"); 
    Kirja kirja2 = new Kirja(); kirja2.parse("2|Täällä pohjantähden alla|jaakko jaakonpoika|suomi   |WSOY |2004|343-467-0-23456-1 |200 |fantasia|"); 
    Kirja kirja3 = new Kirja(); kirja3.parse("3|Tuntematon sotilas      |essi esimerkki    |suomi   |WSOY |1985|752-123-2-34658-5 |489 |kaunokirjallisuus|"); 
    Kirja kirja4 = new Kirja(); kirja4.parse("4|Rautatie                |Juhani Aho"); 
    Kirja kirja5 = new Kirja(); kirja5.parse("5|Harry Potter            |Rowling"); 
    kirjasto.lisaa(kirja1); kirjasto.lisaa(kirja2); kirjasto.lisaa(kirja3); kirjasto.lisaa(kirja4); kirjasto.lisaa(kirja5); 
    kirjasto.laskeTilastot(ps); 
    String vastaus = ("Kirjoja on kirjastossa: 5\r\n" +
    "Eniten kirjoja on kirjoittanut: essi esimerkki\r\n" +
    "Suosituin genre on: kauhu\r\n" +
    "Pisin kirja on: Tuntematon sotilas\r\n" +
    "Tuorein julkaistu kirja on: Täällä pohjantähden alla\r\n"); 
    assertEquals("From: Kirjasto line: 519", true, outContent.toString().equals(vastaus)); 
  } // Generated by ComTest END
}