package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.09 19:06:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi83 */
  @Test
  public void testRekisteroi83() {    // Kirja: 83
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 85", 0, kirja1.getKirjanID()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjanID(); 
    int n2 = kirja2.getKirjanID(); 
    assertEquals("From: Kirja line: 91", n2-1, n1); 
  } // Generated by ComTest END
}