package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.04 17:47:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testParse81 */
  @Test
  public void testParse81() {    // Kirja: 81
    Kirja kirja = new Kirja(); 
    kirja.parse("2  |  Taru sormusten herrasta  |  J R Tolkien  "); 
    assertEquals("From: Kirja line: 84", 2, kirja.getKirjanID()); 
    assertEquals("From: Kirja line: 85", true, kirja.toString().startsWith("2|Taru sormusten herrasta|J R Tolkien|")); 
    kirja.rekisteroi(); 
    int n = kirja.getKirjanID(); 
    kirja.parse("" + (n+20)); 
    kirja.rekisteroi(); 
    assertEquals("From: Kirja line: 91", n+20+1, kirja.getKirjanID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi121 */
  @Test
  public void testRekisteroi121() {    // Kirja: 121
    Kirja kirja1 = new Kirja(); 
    assertEquals("From: Kirja line: 123", 0, kirja1.getKirjanID()); 
    kirja1.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int n1 = kirja1.getKirjanID(); 
    int n2 = kirja2.getKirjanID(); 
    assertEquals("From: Kirja line: 129", n2-1, n1); 
  } // Generated by ComTest END
}