package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 11:19:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa236 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa236() throws SailoException {    // Kirjat: 236
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjat line: 240", 0, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 241", 1, kirjat.getLkm()); 
    kirjat.lisaa(kirja2); assertEquals("From: Kirjat line: 242", 2, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 243", 3, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 244", kirja1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 245", kirja2, kirjat.anna(1)); 
    assertEquals("From: Kirjat line: 246", kirja1, kirjat.anna(2)); 
    assertEquals("From: Kirjat line: 247", false, kirjat.anna(1) == kirja1); 
    assertEquals("From: Kirjat line: 248", true, kirjat.anna(1) == kirja2); 
    try {
    assertEquals("From: Kirjat line: 249", kirja1, kirjat.anna(3)); 
    fail("Kirjat: 249 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 250", 4, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); assertEquals("From: Kirjat line: 251", 5, kirjat.getLkm()); 
    Kirja kirja6 = new Kirja(); 
    kirjat.lisaa(kirja6); assertEquals("From: Kirjat line: 253", 6, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 254", 10, kirjat.taulukonKoko()); 
    kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); 
    kirjat.lisaa(kirja6); kirjat.lisaa(kirja6); 
    assertEquals("From: Kirjat line: 257", 20, kirjat.taulukonKoko()); 
  } // Generated by ComTest END
}