package Kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.22 11:17:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetID68 */
  @Test
  public void testGetID68() {    // Kirja: 68
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 70", 0, kirja.getID()); 
    kirja.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
  } // Generated by ComTest END
}