package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 11:19:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {
    //
}