package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 15:01:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommentitTest {



  // Generated by ComTest BEGIN
  /** testAnnaKommentit60 */
  @Test
  public void testAnnaKommentit60() {    // Kommentit: 60
    Kommentit kommentit = new Kommentit(); 
    Kommentti kom11 = new Kommentti(2); kommentit.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(1); kommentit.lisaa(kom22); 
    Kommentti kom33 = new Kommentti(2); kommentit.lisaa(kom33); 
    Kommentti kom44 = new Kommentti(1); kommentit.lisaa(kom44); 
    Kommentti kom55 = new Kommentti(2); kommentit.lisaa(kom55); 
    Kommentti kom66 = new Kommentti(5); kommentit.lisaa(kom66); 
    List<Kommentti> loytyneet; 
    loytyneet = kommentit.annaKommentit(3); 
    assertEquals("From: Kommentit line: 71", 0, loytyneet.size()); 
    loytyneet = kommentit.annaKommentit(1); 
    assertEquals("From: Kommentit line: 73", 2, loytyneet.size()); 
    assertEquals("From: Kommentit line: 74", true, loytyneet.get(0) == kom22); 
    assertEquals("From: Kommentit line: 75", true, loytyneet.get(1) == kom44); 
    loytyneet = kommentit.annaKommentit(5); 
    assertEquals("From: Kommentit line: 77", 1, loytyneet.size()); 
    assertEquals("From: Kommentit line: 78", true, loytyneet.get(0) == kom66); 
  } // Generated by ComTest END
}