package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 15:01:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommenttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi40 */
  @Test
  public void testRekisteroi40() {    // Kommentti: 40
    Kommentti kom1 = new Kommentti(); 
    assertEquals("From: Kommentti line: 42", 0, kom1.getKommentinID()); 
    kom1.rekisteroi(); 
    Kommentti kom2 = new Kommentti(); 
    kom2.rekisteroi(); 
    int n1 = kom1.getKommentinID(); 
    int n2 = kom2.getKommentinID(); 
    assertEquals("From: Kommentti line: 48", n2-1, n1); 
  } // Generated by ComTest END
}