package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 14:27:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommentitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta91 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta91() throws SailoException {    // Kommentit: 91
    Kommentit kommentit = new Kommentit(); 
    Kommentti kom1 = new Kommentti(); kom1.taytaKommentinTiedot(2); 
    Kommentti kom2 = new Kommentti(); kom2.taytaKommentinTiedot(1); 
    Kommentti kom3 = new Kommentti(); kom3.taytaKommentinTiedot(2); 
    Kommentti kom4 = new Kommentti(); kom4.taytaKommentinTiedot(1); 
    Kommentti kom5 = new Kommentti(); kom5.taytaKommentinTiedot(2); 
    String tiedNimi = "testikirjasto"; 
    File ftied = new File(tiedNimi + ".dat"); 
    ftied.delete(); 
    try {
    kommentit.lueTiedostosta(tiedNimi); 
    fail("Kommentit: 102 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kommentit.lisaa(kom1); 
    kommentit.lisaa(kom2); 
    kommentit.lisaa(kom3); 
    kommentit.lisaa(kom4); 
    kommentit.lisaa(kom5); 
    kommentit.tallenna(); 
    kommentit = new Kommentit(); 
    kommentit.lueTiedostosta(tiedNimi); 
    ArrayList<Kommentti> testiKom = kommentit.annaKommentit(2); 
    Iterator<Kommentti> i = testiKom.iterator(); 
    assertEquals("From: Kommentit line: 113", kom1.toString(), i.next().toString()); 
    assertEquals("From: Kommentit line: 114", kom3.toString(), i.next().toString()); 
    assertEquals("From: Kommentit line: 115", kom5.toString(), i.next().toString()); 
    assertEquals("From: Kommentit line: 116", false, i.hasNext()); 
    kommentit.lisaa(kom5); 
    kommentit.tallenna(); 
    assertEquals("From: Kommentit line: 119", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKommentit199 */
  @Test
  public void testAnnaKommentit199() {    // Kommentit: 199
    Kommentit kommentit = new Kommentit(); 
    Kommentti kom11 = new Kommentti(2); kommentit.lisaa(kom11); 
    Kommentti kom22 = new Kommentti(1); kommentit.lisaa(kom22); 
    Kommentti kom33 = new Kommentti(2); kommentit.lisaa(kom33); 
    Kommentti kom44 = new Kommentti(1); kommentit.lisaa(kom44); 
    Kommentti kom55 = new Kommentti(2); kommentit.lisaa(kom55); 
    Kommentti kom66 = new Kommentti(5); kommentit.lisaa(kom66); 
    List<Kommentti> loytyneet; 
    loytyneet = kommentit.annaKommentit(3); 
    assertEquals("From: Kommentit line: 210", 0, loytyneet.size()); 
    loytyneet = kommentit.annaKommentit(1); 
    assertEquals("From: Kommentit line: 212", 2, loytyneet.size()); 
    assertEquals("From: Kommentit line: 213", true, loytyneet.get(0) == kom22); 
    assertEquals("From: Kommentit line: 214", true, loytyneet.get(1) == kom44); 
    loytyneet = kommentit.annaKommentit(5); 
    assertEquals("From: Kommentit line: 216", 1, loytyneet.size()); 
    assertEquals("From: Kommentit line: 217", true, loytyneet.get(0) == kom66); 
  } // Generated by ComTest END
}