package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.04 18:47:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommenttiTest {



  // Generated by ComTest BEGIN
  /** testParse41 */
  @Test
  public void testParse41() {    // Kommentti: 41
    Kommentti kommentti = new Kommentti(); 
    kommentti.parse("4  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    assertEquals("From: Kommentti line: 44", 4, kommentti.getKommentinID()); 
    assertEquals("From: Kommentti line: 45", true, kommentti.toString().startsWith("4|2|otsikko212|tekstiätekstiä|")); 
    kommentti.rekisteroi(); 
    int n = kommentti.getKommentinID(); 
    kommentti.parse("" + (n+20)); 
    kommentti.rekisteroi(); 
    assertEquals("From: Kommentti line: 51", n+20+1, kommentti.getKommentinID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi91 */
  @Test
  public void testRekisteroi91() {    // Kommentti: 91
    Kommentti kom1 = new Kommentti(); 
    assertEquals("From: Kommentti line: 93", 0, kom1.getKommentinID()); 
    kom1.rekisteroi(); 
    Kommentti kom2 = new Kommentti(); 
    kom2.rekisteroi(); 
    int n1 = kom1.getKommentinID(); 
    int n2 = kom2.getKommentinID(); 
    assertEquals("From: Kommentti line: 99", n2-1, n1); 
  } // Generated by ComTest END
}