package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 13:35:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KommenttiTest {



  // Generated by ComTest BEGIN
  /** testParse49 */
  @Test
  public void testParse49() {    // Kommentti: 49
    Kommentti kommentti = new Kommentti(); 
    kommentti.parse("4  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    assertEquals("From: Kommentti line: 52", 4, kommentti.getKommentinID()); 
    assertEquals("From: Kommentti line: 53", true, kommentti.toString().startsWith("4|2|otsikko212|tekstiätekstiä|")); 
    kommentti.rekisteroi(); 
    int n = kommentti.getKommentinID(); 
    kommentti.parse("" + (n+20)); 
    kommentti.rekisteroi(); 
    assertEquals("From: Kommentti line: 59", n+20+1, kommentti.getKommentinID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone84 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone84() throws CloneNotSupportedException {    // Kommentti: 84
    Kommentti kommentti = new Kommentti(); 
    kommentti.parse("4  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    Kommentti kopio = kommentti.clone(); 
    assertEquals("From: Kommentti line: 89", kommentti.toString(), kopio.toString()); 
    kommentti.parse("2  | 4 |  123  |  sdfsdf  "); 
    assertEquals("From: Kommentti line: 91", false, kopio.toString().equals(kommentti.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString115 */
  @Test
  public void testToString115() {    // Kommentti: 115
    Kommentti kom = new Kommentti(); 
    kom.parse("4  | 2 |  otsikko212  |  tekstiätekstiä  "); 
    assertEquals("From: Kommentti line: 118", "4|2|otsikko212|tekstiätekstiä|", kom.toString()); 
    kom.parse("56  | 23 |  otsikko  |  teksti  "); 
    assertEquals("From: Kommentti line: 120", "56|23|otsikko|teksti|", kom.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi137 */
  @Test
  public void testRekisteroi137() {    // Kommentti: 137
    Kommentti kom1 = new Kommentti(); 
    assertEquals("From: Kommentti line: 139", 0, kom1.getKommentinID()); 
    kom1.rekisteroi(); 
    Kommentti kom2 = new Kommentti(); 
    kom2.rekisteroi(); 
    int n1 = kom1.getKommentinID(); 
    int n2 = kom2.getKommentinID(); 
    assertEquals("From: Kommentti line: 145", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKommentti243 */
  @Test
  public void testKommentti243() {    // Kommentti: 243
    Kommentti kom = new Kommentti(5); 
    assertEquals("From: Kommentti line: 245", 5, kom.getKirjanID()); 
    Kommentti kom2 = new Kommentti(12); 
    assertEquals("From: Kommentti line: 247", 12, kom2.getKirjanID()); 
  } // Generated by ComTest END
}